#!/bin/bash

for dir in `ls` ; do 
  if [ -d $dir ]; then
    for eprimefile in $dir/*.eprime ; do  
      for paramfile in $dir/*.param ; do 
        if [ -e $paramfile ]; then
          ../savilerow -in-eprime $eprimefile -in-param $paramfile || { echo $dir; echo $eprimefile; echo $paramfile; exit; }
        else
          ../savilerow -in-eprime $eprimefile || { echo $dir; echo $eprimefile; echo $paramfile; exit; }
        fi
      done 
    done
  fi
done

